title:               Every Captive Thought
url:                 http://everycaptivethought.com
baseurl:             "http://everycaptivethought.com/blog"

markdown:            kramdown
highlighter:         rouge

exclude:             ['*.sublime-*', 'README.md', 'LICENSE', 'Gemfile', 'Gemfile.lock', 'vendor/bundle']

permalink:           pretty
paginate:            5
paginate_path:       /blog/:num

sass:
  sass_dir:          _sass
  style:             :compressed

author:
  name:              Kevin Behringer
  url:               everycaptivethought.com
  email:             kevinbehringer@gmail.com

plugins:
  - jekyll-coffeescript
  - jekyll-paginate
  - jekyll-gist
